"""PUBLISHABLE figures, generated by Python (matplotlib), never captured
from a browser rendering.

A capture of an ECharts chart depends on the display state at the moment
of the click: light or dark theme, window size, the font actually loaded.
A figure in an article must be reproducible identically from the same
data, which a Python script guarantees and a screenshot never does.

`render_figure` is the single entry point: the chart TYPE decides which
internal function is called, but the caller (the FastAPI router) only has
one function to know.
"""

from .render import FigureError, render_figure
from .world import atlas_name, render_world_map
from .charts import (render_dendrogram, render_density_map, render_thematic_evolution,
                     render_three_fields, render_treemap, render_word_cloud)
from .network import render_network

__all__ = ["render_figure", "FigureError", "render_network", "render_world_map",
           "atlas_name", "render_treemap", "render_word_cloud", "render_three_fields",
           "render_thematic_evolution", "render_dendrogram", "render_density_map"]
